In [1]:
top=5000

In [2]:
with open('ltrc_yahoo/set1.train.txt') as f:
    lines = f.readlines()
for i in range(len(lines)):
    lines[i]=lines[i].rstrip(lines[i][-1])
    #print(lines[i])
# Initialize lists to store the data

train_feature_matrix = []
train_doclist_ranges = []
train_label_vector = []
cc=0
dist_qid=[]
for line in lines:
    cc=cc+1
    if(cc>top):
        break
    if not line:
        continue  # Skip empty lines

    parts = line.split()  # Split line by space
    # Extract the label, qid, and features
    label = int(parts[0])
    qid = int(parts[1].split(":")[1])
    if(qid not in dist_qid):
        dist_qid.append(qid)
    present_feature= []
    for i in range(2,len(parts)):
        present_feature.append([int(parts[i].split(":")[0]),float(parts[i].split(":")[1])])
    #print(present_feature)
    k=0
    features=[]
    for i in range(1,700):
        if(k<len(present_feature)):
            if(i==present_feature[k][0]):
                features.append(present_feature[k][1])
                k=k+1
            else:
                features.append(0)
        else:
            features.append(0)
    #features = [float(part.split(":")[1]) for part in parts[2:]]
    
    # Append label to the label vector
    train_label_vector.append(label)

    # Append features to the feature matrix
    train_feature_matrix.append(features)

    # Append the range of documents for this query
    train_doclist_ranges.append(qid)
#print(feature_matrix[0])
# Convert the lists to NumPy arrays (if using NumPy)

import numpy as np
train_feature_matrix = np.array(train_feature_matrix)
train_label_vector = np.array(train_label_vector)
train_doclist_ranges= np.array(train_doclist_ranges)
#print(train_doclist_ranges)
dict_qid={}
for i in range(len(dist_qid)):
    if(dist_qid[i] not in dict_qid.keys()):
        dict_qid[dist_qid[i]]=0
    for j in range(len(train_doclist_ranges)):
        if(dist_qid[i] == train_doclist_ranges[j]):
            dict_qid[dist_qid[i]]=dict_qid[dist_qid[i]]+1
qid_list=list(dict_qid.keys())
n=len(qid_list)
#print(dict_qid)
cum_qid_dict={}
s=0
for j in range(n):
    s=s+dict_qid[qid_list[j]]
    cum_qid_dict[qid_list[j]]=s
#print(cum_qid_dict)

for j in range(len(train_doclist_ranges)):
    train_doclist_ranges[j]=cum_qid_dict[train_doclist_ranges[j]]

    



NotADirectoryError: [Errno 20] Not a directory: 'ltrc_yahoo/set1.train.txt'

In [3]:
train_doclist_ranges

NameError: name 'train_doclist_ranges' is not defined

In [69]:
print(dist_qid)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 22

In [70]:
dict_qid

{1: 1,
 2: 13,
 3: 5,
 4: 8,
 5: 19,
 6: 12,
 7: 18,
 8: 5,
 9: 14,
 10: 13,
 11: 8,
 12: 9,
 13: 16,
 14: 11,
 15: 21,
 16: 14,
 17: 21,
 18: 9,
 19: 14,
 20: 11,
 21: 20,
 22: 18,
 23: 13,
 24: 20,
 25: 22,
 26: 22,
 27: 13,
 28: 17,
 29: 10,
 30: 13,
 31: 12,
 32: 13,
 33: 13,
 34: 23,
 35: 18,
 36: 13,
 37: 20,
 38: 12,
 39: 22,
 40: 14,
 41: 13,
 42: 23,
 43: 13,
 44: 14,
 45: 14,
 46: 5,
 47: 13,
 48: 15,
 49: 14,
 50: 14,
 51: 16,
 52: 16,
 53: 15,
 54: 21,
 55: 22,
 56: 10,
 57: 22,
 58: 18,
 59: 25,
 60: 16,
 61: 12,
 62: 12,
 63: 15,
 64: 15,
 65: 25,
 66: 13,
 67: 9,
 68: 12,
 69: 8,
 70: 16,
 71: 25,
 72: 19,
 73: 24,
 74: 12,
 75: 16,
 76: 10,
 77: 16,
 78: 9,
 79: 17,
 80: 15,
 81: 7,
 82: 9,
 83: 15,
 84: 14,
 85: 16,
 86: 17,
 87: 8,
 88: 17,
 89: 12,
 90: 18,
 91: 23,
 92: 10,
 93: 12,
 94: 12,
 95: 4,
 96: 14,
 97: 12,
 98: 15,
 99: 27,
 100: 16,
 101: 20,
 102: 13,
 103: 19,
 104: 13,
 105: 17,
 106: 17,
 107: 16,
 108: 12,
 109: 15,
 110: 14,
 111: 14,
 112: 19,
 11

In [71]:
with open('ltrc_yahoo/set1.test.txt') as f:
    lines = f.readlines()
for i in range(len(lines)):
    lines[i]=lines[i].rstrip(lines[i][-1])
    #print(lines[i])
# Initialize lists to store the data

test_feature_matrix = []
test_doclist_ranges = []
test_label_vector = []
cc=0
dist_qid=[]
for line in lines:
    cc=cc+1
    if(cc>top):
        break
    if not line:
        continue  # Skip empty lines

    parts = line.split()  # Split line by space
    # Extract the label, qid, and features
    label = int(parts[0])
    qid = int(parts[1].split(":")[1])
    if(qid not in dist_qid):
        dist_qid.append(qid)
    present_feature= []
    for i in range(2,len(parts)):
        present_feature.append([int(parts[i].split(":")[0]),float(parts[i].split(":")[1])])
    #print(present_feature)
    k=0
    features=[]
    for i in range(1,700):
        if(k<len(present_feature)):
            if(i==present_feature[k][0]):
                features.append(present_feature[k][1])
                k=k+1
            else:
                features.append(0)
        else:
            features.append(0)
    #features = [float(part.split(":")[1]) for part in parts[2:]]
    
    # Append label to the label vector
    test_label_vector.append(label)

    # Append features to the feature matrix
    test_feature_matrix.append(features)

    # Append the range of documents for this query
    test_doclist_ranges.append(qid)
#print(feature_matrix[0])
# Convert the lists to NumPy arrays (if using NumPy)

import numpy as np
test_feature_matrix = np.array(test_feature_matrix)
test_label_vector = np.array(test_label_vector)
test_doclist_ranges= np.array(test_doclist_ranges)
#print(test_doclist_ranges)
dict_qid={}
for i in range(len(dist_qid)):
    if(dist_qid[i] not in dict_qid.keys()):
        dict_qid[dist_qid[i]]=0
    for j in range(len(test_doclist_ranges)):
        if(dist_qid[i] == test_doclist_ranges[j]):
            dict_qid[dist_qid[i]]=dict_qid[dist_qid[i]]+1
qid_list=list(dict_qid.keys())
n=len(qid_list)
#print(dict_qid)
cum_qid_dict={}
s=0
for j in range(n):
    s=s+dict_qid[qid_list[j]]
    cum_qid_dict[qid_list[j]]=s
print(cum_qid_dict)

for j in range(len(test_doclist_ranges)):
    test_doclist_ranges[j]=cum_qid_dict[test_doclist_ranges[j]]

    


{22939: 23, 22940: 37, 22941: 57, 22942: 79, 22943: 93, 22944: 102, 22945: 120, 22946: 129, 22947: 143, 22948: 151, 22949: 167, 22950: 186, 22951: 197, 22952: 217, 22953: 231, 22954: 246, 22955: 254, 22956: 271, 22957: 279, 22958: 294, 22959: 311, 22960: 326, 22961: 343, 22962: 362, 22963: 378, 22964: 395, 22965: 413, 22966: 434, 22967: 448, 22968: 462, 22969: 473, 22970: 496, 22971: 503, 22972: 521, 22973: 535, 22974: 552, 22975: 566, 22976: 588, 22977: 599, 22978: 610, 22979: 629, 22980: 647, 22981: 653, 22982: 676, 22983: 694, 22984: 708, 22985: 719, 22986: 736, 22987: 752, 22988: 767, 22989: 788, 22990: 803, 22991: 813, 22992: 826, 22993: 843, 22994: 868, 22995: 891, 22996: 912, 22997: 924, 22998: 935, 22999: 954, 23000: 965, 23001: 981, 23002: 996, 23003: 1018, 23004: 1030, 23005: 1045, 23006: 1066, 23007: 1079, 23008: 1095, 23009: 1111, 23010: 1127, 23011: 1142, 23012: 1159, 23013: 1172, 23014: 1195, 23015: 1210, 23016: 1232, 23017: 1243, 23018: 1261, 23019: 1280, 23020: 1291, 23

In [72]:
print(test_feature_matrix)

[[0.74142  0.       0.       ... 0.046567 0.       0.11245 ]
 [0.       0.       0.       ... 0.046567 0.86567  0.10183 ]
 [0.       0.       0.       ... 0.046567 0.61889  0.77157 ]
 ...
 [0.       0.       0.       ... 0.046567 0.       0.97348 ]
 [0.       0.       0.       ... 0.046567 0.       0.85936 ]
 [0.       0.       0.       ... 0.046567 0.       0.97696 ]]


In [73]:
print(test_label_vector)

[0 1 1 ... 2 1 1]


In [74]:
test_doclist_ranges

array([  23,   23,   23, ..., 5000, 5000, 5000])

In [77]:
with open('ltrc_yahoo/set1.valid.txt') as f:
    lines = f.readlines()
for i in range(len(lines)):
    lines[i]=lines[i].rstrip(lines[i][-1])
    #print(lines[i])
# Initialize lists to store the data

valid_feature_matrix = []
valid_doclist_ranges = []
valid_label_vector = []
cc=0
dist_qid=[]
for line in lines:
    cc=cc+1
    if(cc>top):
        break
    if not line:
        continue  # Skip empty lines

    parts = line.split()  # Split line by space
    # Extract the label, qid, and features
    label = int(parts[0])
    qid = int(parts[1].split(":")[1])
    if(qid not in dist_qid):
        dist_qid.append(qid)
    present_feature= []
    for i in range(2,len(parts)):
        present_feature.append([int(parts[i].split(":")[0]),float(parts[i].split(":")[1])])
    #print(present_feature)
    k=0
    features=[]
    for i in range(1,700):
        if(k<len(present_feature)):
            if(i==present_feature[k][0]):
                features.append(present_feature[k][1])
                k=k+1
            else:
                features.append(0)
        else:
            features.append(0)
    #features = [float(part.split(":")[1]) for part in parts[2:]]
    
    # Append label to the label vector
    valid_label_vector.append(label)

    # Append features to the feature matrix
    valid_feature_matrix.append(features)

    # Append the range of documents for this query
    valid_doclist_ranges.append(qid)
#print(feature_matrix[0])
#Convert the lists to NumPy arrays (if using NumPy)

import numpy as np
valid_feature_matrix = np.array(valid_feature_matrix)
valid_label_vector = np.array(valid_label_vector)
valid_doclist_ranges= np.array(valid_doclist_ranges)
#print(valid_doclist_ranges)

dict_qid={}
for i in range(len(dist_qid)):
    if(dist_qid[i] not in dict_qid.keys()):
        dict_qid[dist_qid[i]]=0
    for j in range(len(valid_doclist_ranges)):
        if(dist_qid[i] == valid_doclist_ranges[j]):
            dict_qid[dist_qid[i]]=dict_qid[dist_qid[i]]+1
qid_list=list(dict_qid.keys())
n=len(qid_list)
#print(dict_qid)

cum_qid_dict={}
s=0
for j in range(n):
    s=s+dict_qid[qid_list[j]]
    cum_qid_dict[qid_list[j]]=s
#print(cum_qid_dict)

for j in range(len(valid_doclist_ranges)):
    valid_doclist_ranges[j]=cum_qid_dict[valid_doclist_ranges[j]]


In [76]:
valid_doclist_ranges

array([  18,   18,   18, ..., 5000, 5000, 5000])

In [6]:


# Specify the path where you want to save the .npz file
output_file = "set1.binarized_purged_querynorm_filtered.npz"

# Save the arrays to the .npz file
np.savez(output_file, train_feature_matrix=train_feature_matrix, train_label_vector=train_label_vector ,train_doclist_ranges= train_doclist_ranges,
         test_feature_matrix=test_feature_matrix, test_label_vector=test_label_vector,test_doclist_ranges= test_doclist_ranges,
         valid_feature_matrix=valid_feature_matrix, valid_label_vector=valid_label_vector,valid_doclist_ranges= valid_doclist_ranges)
